Repository smartguy-coder/AWESOME-FASTAPI-PROJECT, pull requests merged in 2023-11, with the labels that each got.

#1 Update .gitignore
  .gitignore
Labels: enhancement

#3 checking branch names
  .github/workflows/check-branch-names.yml
Labels: infrastucture

#4 fix Makefile for creating virtualenv
   app/api/.gitkeep
   app/storage/no_sql_storage/.gitkeep
   app/utils/.gitkeep
   app/web/.gitkeep
  Makefile
  pyproject.toml
  tests/.gitkeep
Labels: bug, infrastucture

#7 Dev 4 1
  Makefile
  docs/auth.md
  docs/db_connection.md
  docs/deploy.md
  docs/img/avatar.jpg
  docs/index.md
  docs/used_ports.md
  mkdocs.yml
  poetry.lock
  pyproject.toml
Labels: enhancement

#5 DEV-5: create first endpoint
   app/storage/no_sql_storage/.gitkeep
  .env-example
  Makefile
  app/api/api_router.py
  app/main.py
  app/settings.py
  app/storage/no_sql_storage/.gitkeep
  app/utils/.gitkeep
  app/web/.gitkeep
  poetry.lock
  pyproject.toml
Labels: enhancement
